replace api version check with specific feature checks
ysde/grafana-backup-tool pull request #117
Opened 2020-12-29 03:55 UTC by acjohnson

* ensure compat with hide_version Grafana setting

2020-12-29 03:55 UTC, acjohnson commented
Fixes #94

2020-12-29 03:56 UTC, acjohnson commented
This also fixes issues with missing `uid` dashboard and folder keys in Grafana version < 5.0.0

2021-01-04 21:38 UTC, acjohnson commented
@ysde let me know if you have any questions

2021-01-05 16:17 UTC, acjohnson commented
@Mikey1993 any comments on this as it relates to https://github.com/ysde/grafana-backup-tool/issues/94#issuecomment-751502021

2021-01-08 16:18 UTC, Mikey1993 requested changes
@acjohnson ,
I suggest changing the `paging_feature_check` to be something like this:

```
def paging_feature_check(grafana_url, http_get_headers, verify_ssl, client_cert, debug):
    def get_first_dashboard_by_page(page):
        (status, content) = search_dashboard(page, 1, grafana_url, http_get_headers, verify_ssl, client_cert, debug)
        if status == 200 and len(content):
            dashboard_values = sorted(content[0].items(), key=lambda kv: str(kv[1]))
            return True, dashboard_values
        else:
            if len(content):
                return "get dashboards failed, status: {0}, msg: {1}".format(status, content)
            else:
                # No dashboards exist, disable paging feature
                return False

    # Get first dashboard on first page
    (status, content) = get_first_dashboard_by_page(1)
    if status is False:
        return False  # Paging feature not supported
    elif status is True:
        dashboard_one_values = content
    else:
        return content  # Fail Message

    # Get second dashboard on second page
    (status, content) = get_first_dashboard_by_page(2)
    if status is False:
        return False  # Paging feature not supported
    elif status is True:
        dashboard_two_values = content
    else:
        return content  # Fail Message

    # Compare both pages
    return dashboard_one_values != dashboard_two_values
```

2021-01-11 20:40 UTC, acjohnson commented
@Mikey1993 I tested and corrected your stylistic refactor of `paging_feature_check` and added it to this PR

2021-01-11 20:42 UTC, acjohnson commented
@ysde any heartburn with merging this one?

2021-01-12 03:41 UTC, acjohnson commented on grafana_backup/save_folders.py
> +                folder_uri = folder['uri']
@ysde fair question but no this does not affect the backup or restore function. Backups created using previous versions of `grafana-backup-tool` will still be valid.

Also note that `uid_support` is available on all Grafana versions 5.0.0 and newer

2021-01-12 04:26 UTC, merged